name: Frontend Build CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. checkout
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Node 环境
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # 3. 安装依赖
      - name: Install dependencies
        run: npm install

      # 4. 构建
      - name: Build project
        run: npm run build
